In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
from sklearn import cross_validation
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [5]:
df_origin = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/train.csv')

In [3]:
df_origin['Product_Info_2'] = df_origin['Product_Info_2'].apply(lambda x: 0)
df_test['Product_Info_2'] = df_test['Product_Info_2'].apply(lambda x: 0)

In [ ]:
# df_origin.head()

In [6]:
df_origin.tail(24)

,Id,Product_Info_1,Product_Info_2,Product_Info_3,Product_Info_4,Product_Info_5,Product_Info_6,Product_Info_7,Ins_Age,Ht,...,Medical_Keyword_40,Medical_Keyword_41,Medical_Keyword_42,Medical_Keyword_43,Medical_Keyword_44,Medical_Keyword_45,Medical_Keyword_46,Medical_Keyword_47,Medical_Keyword_48,Response
59357,79121,1,D3,26,1.000000,2,1,3,0.582090,0.781818,...,0,0,0,0,0,0,0,0,0,6
59358,79122,1,D4,26,0.282051,2,3,1,0.238806,0.727273,...,0,0,0,0,0,0,0,0,0,6
59359,79123,1,D3,26,0.230769,2,3,1,0.447761,0.781818,...,0,0,0,0,1,0,0,0,0,6
59360,79124,1,D4,26,1.000000,2,3,1,0.194030,0.654545,...,0,0,0,0,0,0,0,0,0,5
59361,79126,1,A1,26,0.230769,2,1,1,0.268657,0.727273,...,0,0,0,0,0,0,0,0,0,2
59362,79127,1,D4,26,0.230769,2,3,1,0.253731,0.781818,...,0,0,0,0,0,0,0,0,0,7
59363,79128,1,D2,4,0.076923,2,3,1,0.746269,0.563636,...,0,0,0,0,0,0,0,0,0,6
59364,79130,1,D2,26,0.076923,2,3,1,0.552239,0.727273,...,0,0,0,0,0,0,0,0,0,1
59365,79131,1,D1,29,0.076923,2,3,1,0.641791,0.709091,...,0,0,0,0,0,0,0,0,0,5
59366,79132,1,D1,26,0.282051,2,3,1,0.582090,0.781818,...,0,0,0,0,0,0,0,0,0,8
59367,79133,1,E1,26,0.179487,2,3,3,0.373134,0.600000,...,0,0,0,0,0,0,0,0,0,6
59368,79134,1,D4,26,0.230769,2,1,1,0.417910,0.727273,...,0,0,0,0,0,0,0,0,0,8
59369,79135,1,D1,26,0.179487,2,3,1,0.611940,0.745455,...,0,0,0,0,0,0,0,0,1,2
59370,79136,1,D3,26,0.230769,2,3,1,0.238806,0.763636,...,0,0,0,0,0,0,0,0,0,4
59371,79137,1,D3,26,0.487179,2,1,1,0.537313,0.709091,...,0,0,0,0,0,0,0,0,0,6
59372,79138,1,D3,26,0.487179,2,3,1,0.477612,0.763636,...,0,0,1,0,0,0,0,0,1,2
59373,79139,2,D4,29,0.487179,2,3,1,0.208955,0.800000,...,0,0,0,0,0,0,0,0,0,8
59374,79140,1,D4,26,0.307692,2,3,1,0.164179,0.690909,...,0,0,0,0,0,0,0,0,0,7
59375,79141,1,C1,26,0.076923,2,3,1,0.477612,0.654545,...,0,0,0,0,0,0,0,0,0,8
59376,79142,1,D1,10,0.230769,2,3,1,0.074627,0.709091,...,0,0,0,0,0,0,0,0,0,4
59377,79143,1,D3,26,0.230769,2,3,1,0.432836,0.800000,...,0,0,0,0,0,0,0,0,0,7
59378,79144,1,E1,26,0.076923,2,3,1,0.104478,0.745455,...,0,0,0,0,0,0,0,0,0,8
59379,79145,1,D2,10,0.230769,2,3,1,0.507463,0.690909,...,1,0,0,0,0,0,0,0,0,8
59380,79146,1,A8,26,0.076923,2,3,1,0.447761,0.781818,...,0,0,0,0,0,0,0,0,0,7

In [ ]:
len(df_origin.describe().columns.values)

In [ ]:
# df_origin['Product_Info_2'] = df_origin['Product_Info_2'].apply(lambda x: hash(tuple(x)))
df_origin['Product_Info_2'] = df_origin['Product_Info_2'].apply(lambda x: 0)

In [ ]:
fea_cols = df_origin.columns.values[1:-1]

In [ ]:
df_origin[fea_cols].corr()

In [ ]:
df_origin.tail(24)

In [ ]:
df_origin['Response'].hist()

In [ ]:
df_origin['sqrt_response'] = np.log(10 - df_origin['Response'])

In [ ]:
df_origin['sqrt_response'].hist()

In [ ]:
df_origin.columns.values

In [ ]:
df_origin.fillna(0, inplace=True)

In [ ]:
def findNan(df):
    cols = df.columns.values
    print cols
    for c in cols:
        print c, df[c].unique()

findNan(df_origin)

In [ ]:
clf = RandomForestRegressor(n_estimators=100, min_samples_split=11, oob_score=True)

In [ ]:
clf10 = RandomForestRegressor(n_estimators=200, min_samples_split=11, oob_score=True)

In [ ]:
fea_cols

In [ ]:
clf.fit(df_origin[fea_cols].values, df_origin['Response'].values)

In [ ]:
df_test = pd.read_csv('data/test.csv')

In [ ]:
df_test['Product_Info_2'] = df_test['Product_Info_2'].apply(lambda x: 0)
df_test.fillna(0, inplace=True)
pred = clf.predict(df_test[fea_cols])
df_test['Response'] = pred
df_test['Response'] = df_test['Response'].astype(int)

In [ ]:
df_test.to_csv('result1.csv', seq=',', columns=['Id', 'Response'], header=['Id', 'Response'], index = False)

In [ ]:
pd.DataFrame(clf.feature_importances_).plot(kind='bar')
clf.oob_score_

In [ ]:
print clf.feature_importances_
clf_imt = clf.feature_importances_
print [fea_cols[i] for i in range(len(clf_imt)) if clf_imt[i] > 0.003]

In [ ]:
clf_imt = clf.feature_importances_
fea_cols2 = [fea_cols[i] for i in range(len(clf_imt)) if clf_imt[i] > 0.003]

In [ ]:
clf2 = RandomForestRegressor(n_estimators=200, min_samples_split=34, oob_score=True)
clf2.fit(df_origin[fea_cols].values, df_origin['sqrt_response'].values)

In [ ]:
pd.DataFrame(clf2.feature_importances_).plot(kind='bar')
clf2.oob_score_

clf10.fit(df_origin[fea_cols].values, df_origin['Response'].values)

In [ ]:
pd.DataFrame(clf.feature_importances_).plot(kind='bar')
clf10.oob_score_

In [ ]:
pred2 = 10 - np.exp(clf2.predict(df_test[fea_cols]))
pred2 = [round(x) for x in pred2]
df_test['Response'] = pred2
df_test['Response'] = df_test['Response'].astype(int)

In [ ]:
df_test.to_csv('result2.csv', seq=',', columns=['Id', 'Response'], header=['Id', 'Response'], index = False)

In [ ]:
df_tiao = df_origin[0:7000]

11: 0.355
12: 0.359
13: 0.356
14: 0.360
20: 0.363

34

In [ ]:
for i in range(20):
    clf3 = RandomForestRegressor(n_estimators=100, min_samples_split=i * 2 + 22, oob_score=True)
    clf3.fit(df_tiao[fea_cols].values, df_tiao['Response'].values)
    # pd.DataFrame(clf3.feature_importances_).plot(kind='bar')
    print str(i * 2 + 22) + '\t' + str(clf3.oob_score_)